# 작업 디렉토리 관련 설정

- setwd() => 작업 디렉토리 설정
- getwd() => 현재 디렉토리 조회

# 데이터 입출력, 저장
## 데이터 입력
- 데이터 입력 관련 함수, c()를 주로 많이 사용하고, scan이나 edit은 딱히 많이 사용하지 않을 듯
  - c()
    - R 벡터 자료형에 해당(하나 이상의 동일한 데이터타입을 원소로 갖는 집합)
    - 여기서는 원소들을 관측값들이라고 생각하면 될 듯
  - scan()
    - 사용자로부터 입력을 받음(사용자로부터 입력을 받을 수 있음)
  - edit()
    - 사용자로부터 입력을 받음(별도 창이 뜸)
- 갑자기 cbind, rbind 같은 함수도 소개하는데, 함수명에서 나오듯이 열방향 결합함수, 행방향 결합함수

## 데이터 저장
- 데이터를 파일로 출력할수 있는 함수들
  - sink()
    - 이거 사용방법이 좀 독특함, sink() 함수로 출력할 내용 전후에 선언해주어야함
  - write.csv()
    - csv 포맷으로 파일을 저장하게됨
  - write.table()



In [166]:
search()

getwd()

# setwd('/home/centos/apps/server/analysis/base/r-programming')

test1 <- c(1,2,3,4,5)
# test1 변수를 출력하는 방식은 print함수를 써도되고, 그냥 변수명만 넣어도 됨
print(test1)
test1
length(test1) # 5가 나오겠지

# 빈 데이터를 만들수도 있음
test2 <- c()
print(test2)
length(test2)

# cbind, rbind 동작 확인
a <- 1:10
b <- 1:10
print(a)
print(b)
print(cbind(a,b))

## 같은 length의 벡터를 열방향이나 행방향으로 합칠수 있음
c <- rbind(a,b)
print(c)
c <- cbind(a,b)
print(c)


[1] ".GlobalEnv"        "jupyter:irkernel"  "package:stats"    
 [4] "package:graphics"  "package:grDevices" "package:utils"    
 [7] "package:datasets"  "package:methods"   "Autoloads"        
[10] "package:base"

[1] "/home/centos/apps/server/analysis/base/r-programming"

[1] 1 2 3 4 5


[1] 1 2 3 4 5

[1] 5

NULL


[1] 0

 [1]  1  2  3  4  5  6  7  8  9 10
 [1]  1  2  3  4  5  6  7  8  9 10
       a  b
 [1,]  1  1
 [2,]  2  2
 [3,]  3  3
 [4,]  4  4
 [5,]  5  5
 [6,]  6  6
 [7,]  7  7
 [8,]  8  8
 [9,]  9  9
[10,] 10 10
  [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
a    1    2    3    4    5    6    7    8    9    10
b    1    2    3    4    5    6    7    8    9    10
       a  b
 [1,]  1  1
 [2,]  2  2
 [3,]  3  3
 [4,]  4  4
 [5,]  5  5
 [6,]  6  6
 [7,]  7  7
 [8,]  8  8
 [9,]  9  9
[10,] 10 10


In [94]:
# 데이터 입력(벡터)
x <- c(1,2,3,4,5)
x #  [1] 1 2 3 4 5
y <- c(6,6,6,6,6)

# 변수의 데이터타입을 mode 함수로 확인 가능능
mode(x) # numeric
mode(c("a", "b")) # character

# cbind => 길이가 같은 벡터를 하나로 합쳐지게 됨
data <- cbind(x, y)
data

# scan함수 => 입력장치로부터 입력값을 직접 받을수 있음
# 더 입력하지 않는다면 공백에서 엔터 해주면 됨
# 반드시 같은 데이터타입을 넣어줘야함
w1 <- scan()
w1

# edit() 함수 => 아예 데이터 입력창을 별도로 띄워줌(스프레드 시트 같은 윈도)
# 데이터 넣어주고 창 닫으면 들어감
w2 <- data.frame()
w2 <- edit(w2)
w2

# sink() 함수 => 화면에 출력된 모든 결과를 파일로 저장
# sink() 함수 열고, sink() 함수를 다시 써주면 그 사이의 결과가 저장

sink("printa.txt")
summary(iris) # 통계치 계산한 결과가 printa.txt 파일로 생성됨(working directory에 출력력)
sink()

# write.csv() 함수 => 결과를 디렉토리에 저장
write.csv(w2, 'test.csv')

# write.table() 함수 => 디폴트는 구분자 없이 쓰지만, sep(구분자)를 딴거로 지정해서 저장 가능
write.table(w2, 'test2.csv', sep=',,')

# read.csv('test.csv') => csv 파일을 읽어올 수 있음
test <- read.csv('test.csv') 
head(test)

# 데이터의 자료 구조를 보기 위해서 str() 함수 사용(structure의 약자)
str(test)

# 헤더를 T로 주면, 첫번째 줄은 데이터로 인식하지 않고 헤더로 인식한다는 것것
test <- read.table('test.csv', header = T) 
head(test)

# 결측치 => NA (no available), 데이터가 아예 조사되지 않은값(missing value)
# read.table 함수에 na.strings='aa' 라고하면 NA데이터를 모두 aa로 자동 치환해줄수 있음
test2 <- read.table('test.csv', header = T, na.strings = 'aa') 

# ls() 함수 => 현재까지 만들어진 모든 object를 확인 가능
ls()
# [1] "a"     "b"     "c"     "d"     "data"  "data1" "n"     "r"     
# [12] "w1"    "w2"    "x"     "y"     "Z"   

# rm() 함수 호출하면, 모든 object를 삭제 가능
rm(a)
rm(list = ls())

[1] 1 2 3 4 5

[1] "numeric"

[1] "character"

x y
[1,] 1 6
[2,] 2 6
[3,] 3 6
[4,] 4 6
[5,] 5 6

numeric(0)

ERROR: Error in edit(w2): ‘edit()’ not yet supported in the Jupyter R kernel


In [113]:
# 2장 연습문제 풀이

# 2번 문제
familiy <- read.csv("familiy.csv")
head(familiy)

# 3번 문제
head(iris)
str(iris)
iris_mean <- c(mean(iris$Sepal.Length), mean(iris$Sepal.Width), mean(iris$Petal.Length), mean(iris$Petal.Width))
write.csv(iris_mean, file="iris_mean.csv")

# 4번 문제
iris2 <- iris
iris2$Sepal.Ratio <- iris2$Sepal.Length / iris2$Sepal.Width
print(iris2$Sepal.Ratio)

# 6번 문제
rm(list = ls())


height weight
1 170    60.5  
2 180    77.2  
3 165    47.0  
4 171    71.6

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
  [1] 1.457143 1.633333 1.468750 1.483871 1.388889 1.384615 1.352941 1.470588
  [9] 1.517241 1.580645 1.459459 1.411765 1.600000 1.433333 1.450000 1.295455
 [17] 1.384615 1.457143 1.500000 1.342105 1.588235 1.378378 1.277778 1.545455
 [25] 1.411765 1.666667 1.470588 1.485714 1.529412 1.468750 1.548387 1.588235
 [33] 1.268293 1.309524 1.580645 1.562500 1.571429 1.361111 1.466667 1.500000
 [41] 1.428571 1.956522 1.375000 1.428571 1.342105 1.600000 1.342105 1.437500
 [49] 1.432432 1.515152 2.187500 2.000000 2.225806 2.391304 2.321429 2.035714
 [57] 1.909091 2.041667 2.275862 1.925926 2.500000 1.966667 2.727273 2

# 데이터 구조
- 데이터 구조 => 데이터를 관리하는 구조
  - 데이터를 메모리 상에 어떻게 위치시키고 논리적으로 어떻게 이용하는지에 대한 것
  - 단순히 리스트와 배열의 구조를 표현해보면, 물리적 메모리에 연속적이거나 비연속적인 것으로 다르게 관리
    - 물론 이건 각 언어의 구현 방식에 따라서 달라지는 것이므로 절대적으로 이렇게 된다라는 것은 아님

## 벡터
- 1개 이상의 동일한 데이터타입으로 구성된 자료구조
  - 수치형, 문자형, 논리형 중 한가지 형태로만 이루어져야함
- 아래와 같은 함수를 이용하여 벡터 생성 가능
  - c() => c()함수는 어떤 타입도 관계없는데, seq(), req() 함수는 반드시 수치형 데이터가 디폴트임에 주의
  - scan()
  - seq()
  - rep()

## 행렬
- 행렬은 벡터의 확장임
- 동일한 데이터타입으로 구성된 2차원 자료구조
  - 벡터처럼 수치형, 문자형, 논리형 중에 한가지만 가질 수 있음
- matrix()
- cbind()
- rbind()
- 행렬에 대해서 일부 원소 추출, apply, sweep 함수 등을 사용 가능

## 배열
- 행렬을 2차원 이상으로 확장시킨 데이터 구조
  - 물론 1차원으로 사용해도 됨
- array() 함수를 이용

## 리스트
- 서로 다른 데이터타입을 원소로 가질수 있는 데이터 구조

## 데이터프레임
- 데이터 분석시에 많이 사용하는 데이터 구조
- read.table()
- data.frame()
- as.data.frame()



In [165]:
test1 <- c(3:7)
print(test1)

# 흥미로운 것은 수치형 데이터를 넣어도 문자열로 타입이 바뀌어서 저장됨
test2 <- c("1", "KOREA", "TTTT2222 한글", 11)
print(test2)

# seq, rep 함수는 재미있는 다양한 인자를 줄 수가 있음
seq(from = 3, to=7, by=1) # 34567
seq(from = 3, to=7, by=2) # 357

# rep() 함수 이용하기
rep(x = c(1,2,3), times=2) #123123
rep(1:10, each=2) # 각 원소를 2번씩 출력(순서에 주의해야함)
rep(1:5, length=7) #1~5를 반복하긴하는데, 7번째원소까지만 출력

# 함수 용도를 잘 모르겠으면 help 함수를 이용하면 됨, 인자로 함수명을 넣어주면 됨
# help(rep)

v1 <- c(11:20)
v1[c(1,2)] # v1 벡터에서 1, 2번째 원소 추출
v1[v1>15] # v1 벡터에서 15보다 큰 원소 추출
v1[c(-2, -4)] # 이게 용도가 독특한데, 두번째, 네번째 원소를 제외하고 모두 추출

replace(v1, 2, 32) # v1 벡터의 두번째 원소값을 32로 교체

# matrix 함수가 독특한 것이 3행3열 행렬을 만든다고하면, 숫자부여가 열 방향이 디폴트임
mat1 <- matrix(1:9, nrow=3)
print(mat1)

# 행 방향으로 숫자부여하고 싶으면, byrow 인자를 활용할 것
mat2 <- matrix(1:9, nrow=3, byrow = T)
print(mat2)
length(mat2)
mode(mat2)
dim(mat2)

mat3 <- matrix(1:9, nrow=3, byrow=T)
mat3[2,2] # 이건 뭐 기본 연산이지, 2행 2열 원소 추출
mat3[1,] # 1행 원소 출력
mat3[,3] # 3열 원소 출력
mat3[mat3[,3] > 4, ] # 행렬의 3열의 값이 4보다 큰 행렬을 가져오게됨

# 행렬의 원소 단위의 곱셈(행렬의 곱셈과 다름!)
print(mat3 * mat3)
# 아래 연산이 행렬의 곱셈
print(mat3 %*% mat3)
# 전치행렬
t(mat3)

# 배열
arr1 <- array(1:24, c(3,3,2))
print(arr1)


d2 <- read.table("story.txt", header=T, sep = ",")
d2

a1 <- LETTERS[1:20] # 영어 알파벳 대문자 추출
dim(a1) <- c(5,4)
a1

# 행렬을 매트릭스로 아래와 같이 as.data.frame 함수를 이용하여 변환 가능
a2 <- as.data.frame(a1)
print(a2)



[1] 3 4 5 6 7
[1] "1"             "KOREA"         "TTTT2222 한글" "11"           


[1] 3 4 5 6 7

[1] 3 5 7

[1] 1 2 3 1 2 3

[1]  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10

[1] 1 2 3 4 5 1 2

[1] 11 12

[1] 16 17 18 19 20

[1] 11 13 15 16 17 18 19 20

[1] 11 32 13 14 15 16 17 18 19 20

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


[1] 9

[1] "numeric"

[1] 3 3

[1] 5

[1] 1 2 3

[1] 3 6 9

[,1] [,2] [,3]
[1,] 4    5    6   
[2,] 7    8    9

     [,1] [,2] [,3]
[1,]    1    4    9
[2,]   16   25   36
[3,]   49   64   81
     [,1] [,2] [,3]
[1,]   30   36   42
[2,]   66   81   96
[3,]  102  126  150


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18



num name age sex
1 1   Lee  55  M  
2 2   Kwon 57  M  
3 3   Park 12  F  
4 4   Yoon 45  F  
5 5   Kim  34  F

[,1] [,2] [,3] [,4]
[1,] A    F    K    P   
[2,] B    G    L    Q   
[3,] C    H    M    R   
[4,] D    I    N    S   
[5,] E    J    O    T

  V1 V2 V3 V4
1  A  F  K  P
2  B  G  L  Q
3  C  H  M  R
4  D  I  N  S
5  E  J  O  T


In [48]:
# 벡터 => 행렬 => 배열
# 주의할 점이 배열이 컴퓨터 사이언스에서 의미하는 array 개념이 아님
# R 코딩에서 배열이 복수의 행렬로 구성된 자료구조로 이해해야함
# 동일한 행과 열을 가진 행렬을 원소로 가진 집합이 배열이 되는 것
# length - 자료의 개수, mode - 자료의 형태, dim - 각 차원 벡터의 크기, dimnames - 각 차원 리스트의 이름

arr <- array(1:24, c(3,3,2)) 
# 1~18까지의 자료 생성, c(3,3,2) => 3,3,2 사이즈를 가진 자료구조를 만듦, 3행, 3열로 이루어진 행렬을 2개 만든다는 의미
# 독특한 점이 24개의 수를 만드는데 실제 행렬 2개를 만들고 나머지 19~24는 버리고 배열을 만든다는 것

arr

length(arr)

dim(arr)

test2 <- array(1:6)
mode(test2)

# 배열은 숫자만 원소로 가질수 있음
#test3 <- array('a','b')

arr <- c(1:24) # 벡터를 정의하고
dim(arr) <- c(3,4,2) # dim을 이용하면 이걸로 행렬 2개를 만들게 됨
arr

arr <- array(1:8)



, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

[1] 18

[1] 3 3 2

[1] "numeric"

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

In [62]:
# 리스트 => 서로 다른 형태의 데이터로 구성된 객체(문자, 숫자 등 다양한 데이터 타입이 포함 가능)
a <- 1:10
b <- 11:15

klist <- list(vec1=a, vec2 =b, descrip="example")
klist
length(klist)

names(klist)

# 리스트는 인덱스 시작이 1부터 시작함
klist[[1]]
klist$vec1[1]

klist[[2]]

klist$vec1
klist$vec1[1]

klist$vec1[2]

$vec1
 [1]  1  2  3  4  5  6  7  8  9 10

$vec2
[1] 11 12 13 14 15

$descrip
[1] "example"

[1] 3

[1] "vec1"    "vec2"    "descrip"

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1

[1] 11 12 13 14 15

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1

[1] 2